version: '3'
services:
   redis:
     image: redis:7.0.7
     ports:
       - 6379:6379
     volumes:
       - ./redis-data:/data
     networks:
       - static-network
   producer:
     build: . 
     command: python producer.py
     environment:
       OSS_PATH: "/OSS"
       REDIS_HOST: "redis"
       REDIS_PORT: 6379
       QUEUE_NAME: "original"
       LOG_LEVEL: "DEBUG"
     volumes:
       - /OSS:/OSS
   
     networks:
       - static-network
networks:
  static-network:
    name: br-public_nw
    external: true

